apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miller-development
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  source:
    repoURL: https://github.com/org-demo-6za/gitops
    path: components/development/miller # todo apps/development/miller ?
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
